#!/usr/bin/perl -w

use strict;

sub check_add($$) {
  my ($x, $y) = @_;
  my $expected_answer = unpack q{l}, (pack q{l}, ($x + $y) % 2**32);

  my $result = `../build/src/tester/add_tester ../build/src/wasm-examples/addblob/addblob.wasm $x $y`;

  my ($answer) = $result =~ m{^The result is (.*)};

  if ( $answer != $expected_answer ) {
    die qq{Wrong answer to $x + $y ($answer)};
  }
}

for ( 1 .. 32 ) {
  my $x = int rand(2**31);
  my $y = int rand(2**31);
  check_add($x, $y);
}

check_add(0, 0);
check_add(0, -1);
check_add(-1, -1);
check_add(2**32 - 5, 2**31 + 12);
