#!/usr/bin/perl -w

use strict;

if ((scalar @ARGV) != 2) {
  die qq{Usage: $0 wasi_tester addarg.wasm};
}

my ($executable, $wasm) = @ARGV;

sub check_add($$) {
  my ($x, $y) = @_;
  my $expected_answer = unpack q{l}, (pack q{l}, ($x + $y) % 2**32);

  my $result = `$executable $wasm add $x $y 2>&1`;

  if ($?) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Failure in running $x + $y};
  }

  my ($answer) = $result =~ m{^The result is (.*)};

  if ( $answer != $expected_answer ) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Wrong answer to $x + $y ($answer)};
  }
}

for ( 1 .. 8 ) {
  my $x = int rand(2**31);
  my $y = int rand(2**31);
  check_add($x, $y);
}

check_add(0, 0);
check_add(0, -1);
check_add(-1, -1);
check_add(2**32 - 5, 2**31 + 12);
