#!/usr/bin/perl -w

use strict;

if ((scalar @ARGV) != 2) {
  die qq{Usage: $0 wasi_tester helloworld.wasm};
}

my ($executable, $wasm) = @ARGV;

sub check_return($) {
  my ($expected_answer) = @_;

  my $result = `$executable $wasm 2>&1`;

  if ($?) {
    die qq{Failure in running return-test: $result};
  }

  my ($answer) = $result =~ m{^The result is (.*)\nHello, World!};

  if ( $answer != $expected_answer ) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Wrong return value ($answer, was expecting $expected_answer)};
  }
}

check_return(0);
