#!/usr/bin/perl -w

use strict;

if ((scalar @ARGV) != 2) {
  die qq{Usage: $0 stateless-tester addarg.wasm};
}

my ($executable, $wasm) = @ARGV;

sub check_add($$) {
  my ($x, $y) = @_;
  my $x_char = chr($x);
  my $y_char = chr($y);
  my $expected_retval = unpack q{l}, (pack q{l}, ($x + $y) % 2**32);
  my $expected_stdout = "";

  my $result = `$executable tree:3 string:\"0\" thunk: tree:3 string:unused ref:compile-encode file:$wasm tree:3 string:\"add\" string:\"$x_char\" string:\"$y_char\" 2>&1`;

  if ($?) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Failure in running $x + $y};
  }

  my ($answer) = $result =~ m{^The result is (.*)};

  my (undef, $substring) = split( 'Result:\n', $result );
  ($_, my $retval) = $substring =~ m{0\. Blob \(4 bytes\): (.*) \(uint32:(\d*)\)};
  ($_, my $stdout) = $substring =~ m{1\. Blob \((\d*) bytes\): \"(.*)\"};

  if ( !( $retval eq $expected_retval ) or !( $stdout eq $expected_stdout ) ) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Wrong return value ($retval, was expecting $expected_retval)};
  }
}

check_add(48, 48);
check_add(49, 49);
check_add(118, 57);
