#!/usr/bin/perl -w

use strict;

if ((scalar @ARGV) != 2) {
  die qq{Usage: $0 stateless-tester helloworld.wasm};
}

my ($executable, $wasm) = @ARGV;

sub check_return($) {
  my ($expected_retval) = @_;
  my ($expected_stdout) = "Hello, World!";

  my $result = `$executable tree:2 string:\"0\" file:$wasm 2>&1`;

  if ($?) {
    die qq{Failure in running return-test: $result};
  }
  
  my (undef, $substring) = split( 'Result:\n', $result );
  ($_, my $retval) = $substring =~ m{0\. Blob \(4 bytes\): (.*) \(uint32:(\d*)\)};
  ($_, my $stdout) = $substring =~ m{1\. Blob \((\d*) bytes\): \"(.*)\"};

  if ( !( $retval eq $expected_retval ) or !( $stdout eq $expected_stdout ) ) {
    print STDERR qq{Got result:\n$result\n};
    die qq{Wrong return value ($retval, was expecting $expected_retval)};
  }
}

check_return(0);
