// This file was automatically generated by generate.py
// Imports wasm tables, memories, and helper functions from "asm-flatware" and imports fixpoint api functions.
#include "asm-flatware.h"
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
extern void rw_mem_0_to_program_mem( int32_t program_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_0_to_program_mem" ) ) );
extern void rw_mem_1_to_program_mem( int32_t program_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_1_to_program_mem" ) ) );
extern void rw_mem_2_to_program_mem( int32_t program_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_2_to_program_mem" ) ) );
static void (*const rw_to_program_functions[]) ( int32_t, int32_t, int32_t ) = {rw_mem_0_to_program_mem, rw_mem_1_to_program_mem, rw_mem_2_to_program_mem};
void rw_mem_to_program_mem( int32_t rw_mem_id, int32_t program_offset, int32_t rw_offset, int32_t len )
    {
    rw_to_program_functions[rw_mem_id]( program_offset, rw_offset, len );
    }
extern void ro_mem_0_to_program_mem( int32_t program_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_0_to_program_mem" ) ) );
extern void ro_mem_1_to_program_mem( int32_t program_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_1_to_program_mem" ) ) );
extern void ro_mem_2_to_program_mem( int32_t program_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_2_to_program_mem" ) ) );
extern void ro_mem_3_to_program_mem( int32_t program_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_3_to_program_mem" ) ) );
static void (*const ro_to_program_functions[]) ( int32_t, int32_t, int32_t ) = {ro_mem_0_to_program_mem, ro_mem_1_to_program_mem, ro_mem_2_to_program_mem, ro_mem_3_to_program_mem};
void ro_mem_to_program_mem( int32_t ro_mem_id, int32_t program_offset, int32_t ro_offset, int32_t len )
    {
    ro_to_program_functions[ro_mem_id]( program_offset, ro_offset, len );
    }
extern void rw_mem_0_to_flatware_mem( int32_t flatware_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_0_to_flatware_mem" ) ) );
extern void rw_mem_1_to_flatware_mem( int32_t flatware_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_1_to_flatware_mem" ) ) );
extern void rw_mem_2_to_flatware_mem( int32_t flatware_offset, int32_t rw_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "rw_mem_2_to_flatware_mem" ) ) );
static void (*const rw_to_flatware_functions[]) ( int32_t, int32_t, int32_t ) = {rw_mem_0_to_flatware_mem, rw_mem_1_to_flatware_mem, rw_mem_2_to_flatware_mem};
void rw_mem_to_flatware_mem( int32_t rw_mem_id, int32_t flatware_offset, int32_t rw_offset, int32_t len )
    {
    rw_to_flatware_functions[rw_mem_id]( flatware_offset, rw_offset, len );
    }
extern void ro_mem_0_to_flatware_mem( int32_t flatware_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_0_to_flatware_mem" ) ) );
extern void ro_mem_1_to_flatware_mem( int32_t flatware_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_1_to_flatware_mem" ) ) );
extern void ro_mem_2_to_flatware_mem( int32_t flatware_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_2_to_flatware_mem" ) ) );
extern void ro_mem_3_to_flatware_mem( int32_t flatware_offset, int32_t ro_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "ro_mem_3_to_flatware_mem" ) ) );
static void (*const ro_to_flatware_functions[]) ( int32_t, int32_t, int32_t ) = {ro_mem_0_to_flatware_mem, ro_mem_1_to_flatware_mem, ro_mem_2_to_flatware_mem, ro_mem_3_to_flatware_mem};
void ro_mem_to_flatware_mem( int32_t ro_mem_id, int32_t flatware_offset, int32_t ro_offset, int32_t len )
    {
    ro_to_flatware_functions[ro_mem_id]( flatware_offset, ro_offset, len );
    }
extern void program_mem_to_rw_mem_0( int32_t rw_offset, int32_t program_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "program_mem_to_rw_mem_0" ) ) );
extern void program_mem_to_rw_mem_1( int32_t rw_offset, int32_t program_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "program_mem_to_rw_mem_1" ) ) );
extern void program_mem_to_rw_mem_2( int32_t rw_offset, int32_t program_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "program_mem_to_rw_mem_2" ) ) );
static void (*const program_to_rw_functions[]) ( int32_t, int32_t, int32_t ) = {program_mem_to_rw_mem_0, program_mem_to_rw_mem_1, program_mem_to_rw_mem_2};
void program_mem_to_rw_mem( int32_t rw_mem_id, int32_t rw_offset, int32_t program_offset, int32_t len )
    {
    program_to_rw_functions[rw_mem_id]( rw_offset, program_offset, len );
    }
extern void flatware_mem_to_rw_mem_0( int32_t rw_offset, int32_t flatware_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "flatware_mem_to_rw_mem_0" ) ) );
extern void flatware_mem_to_rw_mem_1( int32_t rw_offset, int32_t flatware_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "flatware_mem_to_rw_mem_1" ) ) );
extern void flatware_mem_to_rw_mem_2( int32_t rw_offset, int32_t flatware_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "flatware_mem_to_rw_mem_2" ) ) );
static void (*const flatware_to_rw_functions[]) ( int32_t, int32_t, int32_t ) = {flatware_mem_to_rw_mem_0, flatware_mem_to_rw_mem_1, flatware_mem_to_rw_mem_2};
void flatware_mem_to_rw_mem( int32_t rw_mem_id, int32_t rw_offset, int32_t flatware_offset, int32_t len )
    {
    flatware_to_rw_functions[rw_mem_id]( rw_offset, flatware_offset, len );
    }
#pragma clang diagnostic pop
