// This file was automatically generated by generate.py
// Imports wasm tables, memories, and helper functions from "asm-flatware" and imports fixpoint api functions.
#include "../util/fixpoint_util.h"
#include "api.h"
extern int32_t get_i32_program( int32_t offset )
    __attribute__( (import_module( "asm-flatware" ), import_name( "get_i32_program" ) ) );
extern void set_i32_program( int32_t offset, int32_t value )
    __attribute__( (import_module( "asm-flatware" ), import_name( "set_i32_program" ) ) );
extern int32_t get_i32_flatware( int32_t offset )
    __attribute__( (import_module( "asm-flatware" ), import_name( "get_i32_flatware" ) ) );
extern void set_i32_flatware( int32_t offset, int32_t value )
    __attribute__( (import_module( "asm-flatware" ), import_name( "set_i32_flatware" ) ) );
extern void flatware_mem_to_program_mem( int32_t program_offset, int32_t flatware_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "flatware_mem_to_program_mem" ) ) );
extern void program_mem_to_flatware_mem( int32_t flatware_offset, int32_t program_offset, int32_t len )
    __attribute__( (import_module( "asm-flatware" ), import_name( "program_mem_to_flatware_mem" ) ) );
void rw_mem_to_program_mem( int32_t rw_mem_id, int32_t program_offset, int32_t rw_offset, int32_t len );
void ro_mem_to_program_mem( int32_t ro_mem_id, int32_t program_offset, int32_t ro_offset, int32_t len );
void rw_mem_to_flatware_mem( int32_t rw_mem_id, int32_t flatware_offset, int32_t rw_offset, int32_t len );
void ro_mem_to_flatware_mem( int32_t ro_mem_id, int32_t flatware_offset, int32_t ro_offset, int32_t len );
void program_mem_to_rw_mem( int32_t rw_mem_id, int32_t rw_offset, int32_t program_offset, int32_t len);
void flatware_mem_to_rw_mem( int32_t rw_mem_id, int32_t rw_offset, int32_t flatware_offset, int32_t len);
extern void run_start( void ) __attribute__( ( import_module( "asm-flatware" ), import_name( "run-start" ) ) );
__attribute__( ( noreturn ) ) void flatware_exit( void )
__attribute__( ( import_module( "asm-flatware" ), import_name( "exit" ) ) );
