#ifndef ADDBLOB_H_GENERATED_
#define ADDBLOB_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

typedef struct {
  wasm_rt_memory_t w2c_ro_mem_0;
  wasm_rt_memory_t w2c_ro_mem_1;
  wasm_rt_memory_t w2c_rw_mem_0;
  wasm_rt_table_t w2c_T0;
  uint32_t wasm_rt_call_stack_depth;
} Z_addblob_module_instance_t;

extern void WASM_RT_ADD_PREFIX(init)(Z_addblob_module_instance_t *);

/* import: 'env' 'get_tree_entry' */
extern void (*WASM_RT_ADD_PREFIX(Z_envZ_get_tree_entryZ_viii))(Z_addblob_module_instance_t *, u32, u32, u32);
/* import: 'env' 'attach_blob' */
extern void (*WASM_RT_ADD_PREFIX(Z_envZ_attach_blobZ_vii))(Z_addblob_module_instance_t *, u32, u32);
/* import: 'env' 'detach_mem' */
extern void (*WASM_RT_ADD_PREFIX(Z_envZ_detach_memZ_vii))(Z_addblob_module_instance_t *, u32, u32);
/* import: 'env' 'freeze_blob' */
extern void (*WASM_RT_ADD_PREFIX(Z_envZ_freeze_blobZ_viii))(Z_addblob_module_instance_t *, u32, u32, u32);
/* import: 'env' 'designate_output' */
extern void (*WASM_RT_ADD_PREFIX(Z_envZ_designate_outputZ_vi))(Z_addblob_module_instance_t *, u32);
/* export: '_fixpoint_apply' */
extern void (*WASM_RT_ADD_PREFIX(Z__fixpoint_applyZ_vv))(Z_addblob_module_instance_t *);
/* export: 'ro_mem_0' */
extern wasm_rt_memory_t* WASM_RT_ADD_PREFIX(Z_ro_mem_0)(Z_addblob_module_instance_t *module_instance);
/* export: 'ro_mem_1' */
extern wasm_rt_memory_t* WASM_RT_ADD_PREFIX(Z_ro_mem_1)(Z_addblob_module_instance_t *module_instance);
/* export: 'rw_mem_0' */
extern wasm_rt_memory_t* WASM_RT_ADD_PREFIX(Z_rw_mem_0)(Z_addblob_module_instance_t *module_instance);
#ifdef __cplusplus
}
#endif

#endif  /* ADDBLOB_H_GENERATED_ */
